# Generated by Django 4.2 on 2025-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='preview',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
