# Generated by Django 4.2 on 2025-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='preview',
            field=models.ImageField(upload_to='main/static/main/img', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='main/static/main/img', verbose_name='Изображение'),
        ),
    ]
