# Generated by Django 4.2 on 2025-03-11 12:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_preview_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='preview',
            field=models.ImageField(upload_to='room_previews/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=main.models.room_img_path, verbose_name='Изображение'),
        ),
    ]
