# Generated by Django 4.2 on 2025-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service_alter_roomcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Фото-хранилище номера', 'verbose_name_plural': 'Фото-хранилище номера'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Фото-хранилище услуги', 'verbose_name_plural': 'Фото-хранилище услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='isSpecial',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.ImageField(blank=True, upload_to='services_previews/', verbose_name='Превью'),
        ),
    ]
