# Generated by Django 4.2 on 2025-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_roomimage_options_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preview',
            field=models.ImageField(upload_to='services_previews/', verbose_name='Превью'),
        ),
    ]
