# Generated by Django 4.2 on 2025-04-17 14:09

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConvenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название удобства')),
                ('image', models.ImageField(upload_to=main.models.room_convenience_img_path, verbose_name='Иконка удобства')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='convenience', to='main.room')),
            ],
            options={
                'verbose_name': 'Удобства',
                'verbose_name_plural': 'Удобства',
            },
        ),
    ]
