# Generated by Django 4.2 on 2025-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_roomconvenience'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconvenience',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
