# Generated by Django 4.2 on 2025-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_roomconvenience_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomconvenience',
            name='rooms',
        ),
        migrations.AddField(
            model_name='roomconvenience',
            name='rooms',
            field=models.ManyToManyField(related_name='convenience', to='main.room'),
        ),
    ]
